# Generated by Django 5.2.17 on 2026-08-21 02:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficialScopeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_identifier", models.CharField(max_length=160, unique=True)),
                ("exam_program", models.CharField(default="NEXTGEN_UBE", max_length=40)),
                ("exam_component", models.CharField(default="NEXTGEN_CORE", max_length=40)),
                ("is_national", models.BooleanField(default=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=80)),
                ("normalized_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("validation_report", models.JSONField(blank=True, default=dict)),
                ("is_test_fixture", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="official_scope.officialscopeversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficialScopeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=80)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeversion",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "id"),
            },
        ),
        migrations.CreateModel(
            name="OfficialSourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=160)),
                ("source_authority", models.CharField(max_length=160)),
                ("artifact_type", models.CharField(max_length=80)),
                ("official_title", models.CharField(max_length=300)),
                ("source_uri", models.URLField(blank=True, max_length=1000)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("content_sha256", models.CharField(max_length=64)),
                ("source_version", models.CharField(max_length=160)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("OFFICIAL", "Official"), ("TEST_FIXTURE", "Test fixture")],
                        default="OFFICIAL",
                        max_length=16,
                    ),
                ),
                ("provenance_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="official_scope.officialsourceartifact",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="source_artifacts",
            field=models.ManyToManyField(
                related_name="scope_versions",
                through="official_scope.OfficialScopeSource",
                to="official_scope.officialsourceartifact",
            ),
        ),
        migrations.AddField(
            model_name="officialscopesource",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="official_scope.officialsourceartifact",
            ),
        ),
        migrations.CreateModel(
            name="OfficialScopeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=200)),
                ("official_label", models.CharField(max_length=500)),
                ("official_text", models.TextField(blank=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "perimeter",
                    models.CharField(
                        choices=[
                            ("TESTABLE", "Testable"),
                            ("CONTEXT", "Context"),
                            ("EXCLUDED", "Excluded"),
                            ("UNSPECIFIED", "Unspecified"),
                        ],
                        default="UNSPECIFIED",
                        max_length=16,
                    ),
                ),
                ("subject_group", models.CharField(blank=True, max_length=200)),
                ("is_leaf", models.BooleanField(default=False)),
                ("source_locator", models.CharField(max_length=300)),
                ("treatment_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="official_scope.officialscopeitem",
                    ),
                ),
                (
                    "scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="official_scope.officialscopeversion",
                    ),
                ),
                (
                    "source_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialsourceartifact",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "stable_id"),
            },
        ),
        migrations.AddIndex(
            model_name="officialsourceartifact",
            index=models.Index(
                fields=["source_authority", "artifact_type"], name="official_sc_source__3b3193_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialsourceartifact",
            constraint=models.UniqueConstraint(
                fields=("stable_id", "source_version"), name="official_artifact_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialsourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^[0-9a-f]{64}$")),
                name="official_artifact_sha256_format",
            ),
        ),
        migrations.AddIndex(
            model_name="officialscopeversion",
            index=models.Index(
                fields=["exam_program", "exam_component", "status"],
                name="official_sc_exam_pr_5bf130_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("exam_program", "NEXTGEN_UBE")),
                name="scope_program_nextgen_ube",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("exam_component", "NEXTGEN_CORE")),
                name="scope_component_nextgen_core",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_national", True), ("jurisdiction", "")),
                name="scope_national_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopeversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_test_fixture", False), ("status", "ACTIVE")),
                fields=("exam_program", "exam_component"),
                name="one_active_official_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopesource",
            constraint=models.UniqueConstraint(
                fields=("scope_version", "artifact"), name="scope_artifact_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="officialscopeitem",
            index=models.Index(
                fields=["scope_version", "parent", "ordering"],
                name="official_sc_scope_v_b88072_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="officialscopeitem",
            index=models.Index(
                fields=["scope_version", "is_leaf"], name="official_sc_scope_v_ff9fd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialscopeitem",
            constraint=models.UniqueConstraint(
                fields=("scope_version", "stable_id"), name="scope_item_identity_unique"
            ),
        ),
    ]
