# Generated by Django 5.2.17 on 2026-08-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_scope", "0002_postgres_artifact_immutability"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialsourceartifact",
            name="status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("WITHDRAWN", "Withdrawn")],
                default="PUBLISHED",
                max_length=16,
            ),
        ),
    ]
