# Generated by Django 5.2.17 on 2026-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_scope", "0003_officialsourceartifact_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialscopeitem",
            name="knowledge_treatment",
            field=models.CharField(
                choices=[
                    ("RECALLED_REQUIRED", "Recalled knowledge required"),
                    (
                        "RECOGNITION_WITH_OR_WITHOUT_RESOURCES",
                        "May be tested with or without resources",
                    ),
                    ("RESOURCES_ALWAYS_PROVIDED", "Legal resources always provided"),
                    ("FOUNDATIONAL_SKILL", "Foundational skill"),
                    ("EXAM_DESIGN_METADATA", "Exam design metadata"),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="UNSPECIFIED",
                max_length=48,
            ),
        ),
        migrations.AddField(
            model_name="officialscopeitem",
            name="normalization_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="officialscopeitem",
            name="normalization_status",
            field=models.CharField(
                choices=[
                    ("AUTO_ACCEPTED", "Deterministically accepted"),
                    ("REVIEW_REQUIRED", "Review required"),
                    ("BLOCKED", "Blocked"),
                ],
                default="AUTO_ACCEPTED",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="administration_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="administration_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="freshness_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="normalization_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="officialscopeversion",
            name="release_class",
            field=models.CharField(
                choices=[
                    ("CURRENT", "Current administration period"),
                    ("FUTURE", "Known future administration period"),
                    ("TEST_FIXTURE", "Test fixture"),
                ],
                default="CURRENT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="officialsourceartifact",
            name="byte_length",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialsourceartifact",
            name="effective_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialsourceartifact",
            name="media_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="officialsourceartifact",
            name="rights_basis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="officialsourceartifact",
            name="storage_disposition",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
