# Generated by Django 5.2.17 on 2026-08-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_scope", "0004_officialscopeitem_knowledge_treatment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialscopeitem",
            name="knowledge_treatment",
            field=models.CharField(
                choices=[
                    ("RECALLED_REQUIRED", "Recalled knowledge required"),
                    (
                        "RECOGNITION_WITH_OR_WITHOUT_RESOURCES",
                        "May be tested with or without resources",
                    ),
                    ("RESOURCES_ALWAYS_PROVIDED", "Legal resources always provided"),
                    ("FOUNDATIONAL_SKILL", "Foundational skill"),
                    ("EXAM_DESIGN_METADATA", "Exam design metadata"),
                    (
                        "MIXED_OFFICIAL_MARKERS",
                        "Contains both recalled-only and with-or-without-resource topics",
                    ),
                    ("UNSPECIFIED", "Unspecified"),
                ],
                default="UNSPECIFIED",
                max_length=48,
            ),
        ),
    ]
