# Generated by Django 5.2.17 on 2026-08-21 16:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("official_scope", "0003_officialsourceartifact_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthoritySource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=180)),
                ("source_version", models.CharField(max_length=120)),
                (
                    "authority_class",
                    models.CharField(
                        choices=[
                            ("SUBSTANTIVE_PRIMARY", "Substantive primary"),
                            ("SECONDARY_RECONCILIATION", "Secondary reconciliation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("authority_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=400)),
                ("canonical_citation", models.CharField(max_length=300)),
                ("source_uri", models.URLField(blank=True, max_length=1000)),
                ("content_sha256", models.CharField(max_length=64)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                ("is_national", models.BooleanField(default=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.authoritysource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoveragePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=160)),
                ("policy_version", models.CharField(max_length=80)),
                ("minimum_obligations_per_leaf", models.PositiveSmallIntegerField(default=1)),
                ("requires_primary_authority", models.BooleanField(default=True)),
                ("allowed_obligation_kinds", models.JSONField(default=list)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stable_id", "policy_version"),
                        name="coverage_policy_identity_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_obligations_per_leaf__gte", 1)),
                        name="coverage_policy_minimum_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurriculumCompileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_identifier", models.CharField(max_length=180, unique=True)),
                ("compiler_schema_version", models.CharField(max_length=80)),
                ("input_sha256", models.CharField(max_length=64)),
                ("canonical_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPILED", "Compiled"),
                            ("RECONCILED", "Reconciled"),
                            ("CERTIFIED", "Certified"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                ("compile_report", models.JSONField(blank=True, default=dict)),
                ("reconciliation_report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("compiled_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coverage_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="curriculum.coveragepolicy"
                    ),
                ),
                (
                    "official_scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_compiles",
                        to="official_scope.officialscopeversion",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.curriculumcompileversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageReleaseSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("compiler_schema_version", models.CharField(max_length=80)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                ("obligation_count", models.PositiveIntegerField()),
                ("leaf_count", models.PositiveIntegerField()),
                ("covered_leaf_count", models.PositiveIntegerField()),
                ("blocking_issue_count", models.PositiveIntegerField()),
                ("warning_issue_count", models.PositiveIntegerField()),
                ("coverage_results", models.JSONField()),
                ("certification_sha256", models.CharField(max_length=64, unique=True)),
                ("certified_at", models.DateTimeField()),
                (
                    "official_scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeversion",
                    ),
                ),
                (
                    "compile_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_snapshot",
                        to="curriculum.curriculumcompileversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObligationScopeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mapping_rationale", models.TextField()),
                (
                    "scope_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OMISSION", "Omission"),
                            ("EXCESS", "Excess"),
                            ("CONFLICT", "Conflict"),
                            ("AMBIGUITY", "Ambiguity"),
                            ("DUPLICATE", "Duplicate"),
                            ("UNSUPPORTED_PROVENANCE", "Unsupported provenance"),
                            ("INVALID_STRUCTURE", "Invalid structure"),
                            ("UNSUPPORTED_JURISDICTION", "Unsupported jurisdiction"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("BLOCKING", "Blocking"),
                            ("WARNING", "Warning"),
                            ("INFO", "Information"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "compile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="curriculum.curriculumcompileversion",
                    ),
                ),
                (
                    "scope_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[("ACCEPT", "Accept"), ("REJECT", "Reject"), ("DEFER", "Defer")],
                        max_length=16,
                    ),
                ),
                ("rationale", models.TextField()),
                ("changes_canonical_truth", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_resolution",
                        to="curriculum.reconciliationissue",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RULE", "Rule"),
                            ("ELEMENT", "Element"),
                            ("FACTOR", "Factor"),
                            ("EXCEPTION", "Exception"),
                            ("LIMITATION", "Limitation"),
                            ("DEFENSE", "Defense"),
                            ("REMEDY", "Remedy"),
                            ("PROCEDURAL_STEP", "Procedural step"),
                            ("DISTINCTION", "Distinction"),
                            ("DEFINITION", "Definition"),
                            ("ETHICS_DUTY", "Ethics duty"),
                        ],
                        max_length=24,
                    ),
                ),
                ("normalized_statement", models.TextField()),
                ("statement", models.TextField()),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "compiler_status",
                    models.CharField(
                        choices=[
                            ("INCLUDED", "Included"),
                            ("EXCESS", "Excess"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="INCLUDED",
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("AUTO_APPROVABLE", "Auto approvable"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("BLOCKED", "Blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reconciliation_status", models.CharField(default="UNRECONCILED", max_length=40)),
                ("inclusion_rationale", models.TextField()),
                ("is_core", models.BooleanField(default=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compile_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="curriculum.curriculumcompileversion",
                    ),
                ),
                (
                    "scope_items",
                    models.ManyToManyField(
                        related_name="rule_obligations",
                        through="curriculum.ObligationScopeMapping",
                        to="official_scope.officialscopeitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reconciliationissue",
            name="obligation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="curriculum.ruleobligation",
            ),
        ),
        migrations.AddField(
            model_name="obligationscopemapping",
            name="obligation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="curriculum.ruleobligation"
            ),
        ),
        migrations.CreateModel(
            name="ObligationRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("HAS_ELEMENT", "Has element"),
                            ("HAS_FACTOR", "Has factor"),
                            ("HAS_EXCEPTION", "Has exception"),
                            ("HAS_LIMITATION", "Has limitation"),
                            ("HAS_DEFENSE", "Has defense"),
                            ("HAS_REMEDY", "Has remedy"),
                            ("HAS_PROCEDURAL_STEP", "Has procedural step"),
                            ("HAS_DISTINCTION", "Has distinction"),
                            ("DEFINES", "Defines"),
                            ("HAS_ETHICS_DUTY", "Has ethics duty"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relationships",
                        to="curriculum.ruleobligation",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relationships",
                        to="curriculum.ruleobligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUBSTANTIVE_SUPPORT", "Substantive support"),
                            ("SECONDARY_RECONCILIATION", "Secondary reconciliation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("locator", models.CharField(max_length=300)),
                ("proposition_sha256", models.CharField(max_length=64)),
                ("supports", models.BooleanField(default=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="curriculum.authoritysource"
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_evidence",
                        to="curriculum.ruleobligation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="authoritysource",
            index=models.Index(
                fields=["authority_class", "source_class"], name="curriculum__authori_1bbe4a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritysource",
            constraint=models.UniqueConstraint(
                fields=("stable_id", "source_version"), name="authority_source_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritysource",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^[0-9a-f]{64}$")),
                name="authority_source_sha256_format",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumcompileversion",
            index=models.Index(
                fields=["official_scope_version", "status"], name="curriculum__officia_c84a6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumcompileversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_class", "PRODUCTION"), ("status", "CERTIFIED")),
                fields=("official_scope_version",),
                name="one_certified_curriculum_per_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="ruleobligation",
            index=models.Index(
                fields=["compile_version", "kind", "compiler_status"],
                name="curriculum__compile_7df10d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleobligation",
            constraint=models.UniqueConstraint(
                fields=("compile_version", "stable_id"), name="obligation_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleobligation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("compiler_status", "INCLUDED")),
                fields=("compile_version", "canonical_sha256"),
                name="included_obligation_canonical_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliationissue",
            index=models.Index(
                fields=["compile_version", "severity", "status"],
                name="curriculum__compile_2360ef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reconciliationissue",
            constraint=models.UniqueConstraint(
                fields=("compile_version", "stable_id"), name="reconciliation_issue_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="obligationscopemapping",
            index=models.Index(
                fields=["scope_item", "obligation"], name="curriculum__scope_i_ae5998_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="obligationscopemapping",
            constraint=models.UniqueConstraint(
                fields=("obligation", "scope_item"), name="obligation_scope_mapping_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="obligationrelationship",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "kind"), name="obligation_relationship_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="obligationrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="obligation_relationship_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="authorityevidence",
            index=models.Index(
                fields=["obligation", "role"], name="curriculum__obligat_919df3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="authorityevidence",
            constraint=models.UniqueConstraint(
                fields=("obligation", "authority", "role", "locator"),
                name="authority_evidence_unique",
            ),
        ),
    ]
