# Generated by Django 5.2.17 on 2026-08-21 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0002_postgres_curriculum_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authoritysource",
            name="effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="issuing_authority",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="media_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="rights_basis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="authoritysource",
            name="storage_disposition",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="coveragepolicy",
            name="coverage_class",
            field=models.CharField(
                choices=[
                    ("NATIONAL", "National completeness"),
                    ("PILOT_ONLY", "Bounded pilot only"),
                ],
                default="NATIONAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="coveragepolicy",
            name="requires_human_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coveragepolicy",
            name="target_scope_item_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="authority_provenance_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="coverage_class",
            field=models.CharField(
                choices=[
                    ("NATIONAL", "National completeness"),
                    ("PILOT_ONLY", "Bounded pilot only"),
                ],
                default="NATIONAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="human_review_status",
            field=models.CharField(default="NOT_REQUIRED", max_length=32),
        ),
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="national_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="curriculumcompileversion",
            name="coverage_class",
            field=models.CharField(
                choices=[
                    ("NATIONAL", "National completeness"),
                    ("PILOT_ONLY", "Bounded pilot only"),
                ],
                default="NATIONAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="curriculumcompileversion",
            name="national_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ObligationHumanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")], max_length=16
                    ),
                ),
                ("rationale", models.TextField()),
                ("authority_reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_review",
                        to="curriculum.ruleobligation",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
