# Generated by Django 5.2.17 on 2026-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_authoritysource_effective_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coveragepolicy",
            name="target_scope_item_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
