# Generated by Django 5.2.17 on 2026-08-21 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def install_postgres_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE TRIGGER curriculum_obligation_human_review_no_mutation
            BEFORE UPDATE OR DELETE ON curriculum_obligationhumanreview
            FOR EACH ROW EXECUTE FUNCTION curriculum_reject_immutable_mutation();
            """
        )


def remove_postgres_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            DROP TRIGGER IF EXISTS curriculum_obligation_human_review_no_mutation
            ON curriculum_obligationhumanreview;
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_alter_coveragepolicy_target_scope_item_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="human_review_evidence",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="coveragereleasesnapshot",
            name="human_review_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="obligationhumanreview",
            name="attestation",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="obligationhumanreview",
            name="review_manifest_sha256",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="obligationhumanreview",
            name="reviewer_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="obligationhumanreview",
            name="reviewer_role_qualification",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="obligationhumanreview",
            name="reviewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="obligationhumanreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="obligationhumanreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_manifest_sha256__regex", "^[0-9a-f]{64}$")),
                name="obligation_review_manifest_sha256_format",
            ),
        ),
        migrations.RunPython(install_postgres_trigger, remove_postgres_trigger),
    ]
