# Generated by Django 5.2.17 on 2026-08-21 20:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0005_coveragereleasesnapshot_human_review_evidence_and_more"),
        ("official_scope", "0005_alter_officialscopeitem_knowledge_treatment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeCoverageRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                ("doctrinal_subarea", models.CharField(max_length=300)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("GOVERNING_RULE", "Governing rule"),
                            ("TRIGGERING_CONDITIONS", "Triggering conditions"),
                            ("ELEMENTS_FACTORS", "Elements or factors"),
                            ("EXCEPTIONS_LIMITATIONS", "Exceptions or limitations"),
                            ("PROCEDURAL_BRANCHING", "Procedural branching"),
                            ("CONSEQUENCES_REMEDIES", "Consequences or remedies"),
                            ("DISTINCTIONS_DEFINITIONS", "Distinctions or definitions"),
                            ("DEFENSES", "Defenses"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "treatment_requirement",
                    models.CharField(
                        choices=[
                            ("RECALL", "Recall"),
                            ("RECOGNITION", "Issue recognition without resources"),
                            ("RESOURCE_APPLICATION", "Application with supplied resources"),
                            ("MIXED", "Mixed official treatment"),
                        ],
                        max_length=24,
                    ),
                ),
                ("review_required", models.BooleanField(default=True)),
                ("canonical_sha256", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ("manifest_leaf", "stable_id"),
            },
        ),
        migrations.CreateModel(
            name="CoverageRequirementSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                (
                    "obligation_kind",
                    models.CharField(
                        choices=[
                            ("RULE", "Rule"),
                            ("ELEMENT", "Element"),
                            ("FACTOR", "Factor"),
                            ("EXCEPTION", "Exception"),
                            ("LIMITATION", "Limitation"),
                            ("DEFENSE", "Defense"),
                            ("REMEDY", "Remedy"),
                            ("PROCEDURAL_STEP", "Procedural step"),
                            ("DISTINCTION", "Distinction"),
                            ("DEFINITION", "Definition"),
                            ("ETHICS_DUTY", "Ethics duty"),
                        ],
                        max_length=24,
                    ),
                ),
                ("minimum_count", models.PositiveSmallIntegerField(default=1)),
                ("relationship_expectations", models.JSONField(blank=True, default=list)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="curriculum.scopecoveragerequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectAuthorityPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                ("source_family", models.CharField(max_length=120)),
                (
                    "authority_level",
                    models.CharField(
                        choices=[
                            ("CONTROLLING_CONSTITUTION", "Controlling constitutional text"),
                            ("CONTROLLING_STATUTE", "Controlling federal statute"),
                            ("CONTROLLING_RULE", "Controlling federal rule"),
                            ("BINDING_SUPREME_COURT", "Binding Supreme Court authority"),
                            ("OTHER_PRIMARY", "Other appropriate primary authority"),
                            ("OPTIONAL_SECONDARY", "Optional secondary reconciliation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("planned_title", models.CharField(max_length=400)),
                ("canonical_source_uri", models.URLField(blank=True, max_length=1000)),
                ("version_requirement", models.TextField()),
                ("freshness_requirement", models.TextField()),
                ("drift_action", models.TextField()),
                ("case_authority_required", models.BooleanField(default=False)),
                (
                    "acquisition_status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Acquisition planned"),
                            ("PARTIALLY_ACQUIRED", "Partially acquired"),
                            ("ACQUIRED", "Acquired"),
                        ],
                        default="PLANNED",
                        max_length=24,
                    ),
                ),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "acquired_authority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculum.authoritysource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequirementAuthorityPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required primary authority"),
                            ("CONDITIONAL", "Conditionally required primary authority"),
                            ("OPTIONAL_RECONCILIATION", "Optional reconciliation evidence"),
                        ],
                        max_length=32,
                    ),
                ),
                ("proposition_types", models.JSONField(default=list)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_mappings",
                        to="curriculum.scopecoveragerequirement",
                    ),
                ),
                (
                    "authority_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_mappings",
                        to="curriculum.subjectauthorityplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseAuthorityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                ("proposition_type", models.CharField(max_length=120)),
                (
                    "required_court",
                    models.CharField(default="Supreme Court of the United States", max_length=160),
                ),
                ("exact_case_identity_required", models.BooleanField(default=True)),
                ("decision_date_required", models.BooleanField(default=True)),
                ("reliable_source_uri_required", models.BooleanField(default=True)),
                ("proposition_locator_required", models.BooleanField(default=True)),
                ("authority_status_required", models.BooleanField(default=True)),
                ("later_treatment_review_required", models.BooleanField(default=True)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "authority_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_requirements",
                        to="curriculum.subjectauthorityplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCoveragePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=180)),
                ("policy_version", models.CharField(max_length=80)),
                ("administration_start", models.DateField()),
                ("administration_end", models.DateField()),
                ("requires_primary_authority", models.BooleanField(default=True)),
                ("requires_human_review", models.BooleanField(default=True)),
                ("certification_gate_version", models.CharField(max_length=80)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("REVIEW_PENDING", "Human review pending"),
                            ("APPROVED", "Human approved"),
                            ("REJECTED", "Human rejected"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="REVIEW_PENDING",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "official_scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeversion",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.subjectcoveragepolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectCurriculumManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.CharField(max_length=180)),
                ("manifest_version", models.CharField(max_length=80)),
                ("subject_id", models.CharField(max_length=120)),
                ("subject_label", models.CharField(max_length=240)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "source_class",
                    models.CharField(
                        choices=[("PRODUCTION", "Production"), ("TEST_FIXTURE", "Test fixture")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REVIEW_PENDING", "Human review pending"),
                            ("APPROVED", "Human approved"),
                            ("REJECTED", "Human rejected"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="REVIEW_PENDING",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coverage_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculum.subjectcoveragepolicy",
                    ),
                ),
                (
                    "official_scope_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeversion",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.subjectcurriculummanifest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subjectauthorityplan",
            name="manifest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authority_plans",
                to="curriculum.subjectcurriculummanifest",
            ),
        ),
        migrations.CreateModel(
            name="SubjectManifestLeaf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hierarchy_path", models.JSONField(default=list)),
                ("treatment", models.CharField(max_length=48)),
                (
                    "coverage_status",
                    models.CharField(
                        choices=[
                            ("UNMAPPED", "Unmapped"),
                            ("AUTHORITY_PLANNED", "Authority planned"),
                            ("CANDIDATES_PENDING", "Candidates pending"),
                            ("PARTIALLY_COVERED", "Partially covered"),
                            ("LEAF_CERTIFIED", "Leaf certified"),
                        ],
                        default="UNMAPPED",
                        max_length=24,
                    ),
                ),
                ("review_required", models.BooleanField(default=True)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifest_leaves",
                        to="curriculum.subjectcurriculummanifest",
                    ),
                ),
                (
                    "scope_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeitem",
                    ),
                ),
            ],
            options={
                "ordering": ("scope_item__ordering", "scope_item__stable_id"),
            },
        ),
        migrations.CreateModel(
            name="SubjectCertifiedSubset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contribution_class",
                    models.CharField(default="PARTIAL_LEAF_COVERAGE", max_length=24),
                ),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "coverage_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculum.coveragereleasesnapshot",
                    ),
                ),
                (
                    "manifest_leaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certified_subsets",
                        to="curriculum.subjectmanifestleaf",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scopecoveragerequirement",
            name="manifest_leaf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coverage_requirements",
                to="curriculum.subjectmanifestleaf",
            ),
        ),
        migrations.CreateModel(
            name="SubjectPlanHumanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=200)),
                ("reviewer_role_qualification", models.TextField()),
                (
                    "resolution",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")], max_length=16
                    ),
                ),
                ("rationale", models.TextField()),
                ("attestation", models.TextField()),
                ("review_packet_sha256", models.CharField(max_length=64)),
                ("reviewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "manifest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_review",
                        to="curriculum.subjectcurriculummanifest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageRequirementSatisfaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CERTIFIED", "Certified")],
                        max_length=16,
                    ),
                ),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "coverage_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculum.coveragereleasesnapshot",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="curriculum.ruleobligation"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="satisfactions",
                        to="curriculum.coveragerequirementslot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slot", "obligation"),
                        name="coverage_requirement_satisfaction_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                        name="coverage_satisfaction_sha256_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("coverage_snapshot__isnull", False), ("status", "CERTIFIED")
                        ),
                        name="coverage_satisfaction_certified_snapshot",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="coveragerequirementslot",
            constraint=models.UniqueConstraint(
                fields=("requirement", "stable_id"), name="coverage_requirement_slot_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="coveragerequirementslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_count__gte", 1)),
                name="coverage_requirement_slot_min_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="coveragerequirementslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="coverage_requirement_slot_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementauthorityplan",
            constraint=models.UniqueConstraint(
                fields=("requirement", "authority_plan"), name="requirement_authority_plan_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementauthorityplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="requirement_authority_plan_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseauthorityrequirement",
            constraint=models.UniqueConstraint(
                fields=("authority_plan", "stable_id"), name="case_authority_requirement_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseauthorityrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="case_authority_requirement_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcoveragepolicy",
            constraint=models.UniqueConstraint(
                fields=("stable_id", "policy_version"),
                name="subject_coverage_policy_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcoveragepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_policy_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcurriculummanifest",
            constraint=models.UniqueConstraint(
                fields=("stable_id", "manifest_version"), name="subject_manifest_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcurriculummanifest",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_manifest_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectauthorityplan",
            constraint=models.UniqueConstraint(
                fields=("manifest", "stable_id"), name="subject_authority_plan_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectauthorityplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_authority_plan_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectmanifestleaf",
            constraint=models.UniqueConstraint(
                fields=("manifest", "scope_item"), name="subject_manifest_leaf_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectmanifestleaf",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_manifest_leaf_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcertifiedsubset",
            constraint=models.UniqueConstraint(
                fields=("manifest_leaf", "coverage_snapshot"),
                name="subject_certified_subset_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectcertifiedsubset",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_certified_subset_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopecoveragerequirement",
            constraint=models.UniqueConstraint(
                fields=("manifest_leaf", "stable_id"),
                name="scope_coverage_requirement_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopecoveragerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="scope_requirement_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectplanhumanreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_packet_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_plan_review_packet_sha256_format",
            ),
        ),
    ]
