# Generated by Django 5.2.17 on 2026-08-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0007_postgres_subject_plan_immutability"),
        ("official_scope", "0005_alter_officialscopeitem_knowledge_treatment"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementauthorityplan",
            name="condition_expression",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scopecoveragerequirement",
            name="allowed_obligation_kinds",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scopecoveragerequirement",
            name="required_for_subject_completion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subjectcertifiedsubset",
            name="perimeter_attribution",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subjectmanifestleaf",
            name="classification",
            field=models.CharField(
                choices=[
                    ("LEGACY_OFFICIAL_AGGREGATE", "Legacy coarse official-scope aggregate"),
                    ("CURRICULUM_PLANNING_GROUP", "BarClimb curriculum planning group"),
                ],
                default="LEGACY_OFFICIAL_AGGREGATE",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="scopecoveragerequirement",
            name="treatment_requirement",
            field=models.CharField(
                choices=[
                    ("RECALL", "Recall"),
                    ("RECOGNITION", "Issue recognition without resources"),
                    ("RESOURCE_APPLICATION", "Application with supplied resources"),
                    ("MIXED", "Mixed official treatment"),
                    (
                        "RECOGNITION_WITH_OR_WITHOUT_RESOURCES",
                        "Recognition without resources or application with supplied resources",
                    ),
                ],
                max_length=48,
            ),
        ),
        migrations.CreateModel(
            name="SubjectOfficialTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=220)),
                ("official_label", models.CharField(max_length=500)),
                ("source_locator", models.CharField(max_length=300)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_terminal", models.BooleanField(default=False)),
                (
                    "official_marker",
                    models.CharField(
                        choices=[
                            ("NONE", "Nonterminal hierarchy node"),
                            ("STARRED", "Recalled knowledge required without resources"),
                            ("UNSTARRED", "May be tested with or without resources"),
                        ],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                ("knowledge_treatment", models.CharField(default="UNSPECIFIED", max_length=48)),
                ("administration_start", models.DateField()),
                ("administration_end", models.DateField()),
                ("normalization_notes", models.TextField(blank=True)),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_topics",
                        to="curriculum.subjectcurriculummanifest",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="curriculum.subjectofficialtopic",
                    ),
                ),
                (
                    "planning_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_topics",
                        to="curriculum.subjectmanifestleaf",
                    ),
                ),
                (
                    "root_scope_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialscopeitem",
                    ),
                ),
                (
                    "source_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="official_scope.officialsourceartifact",
                    ),
                ),
            ],
            options={
                "ordering": ("ordering", "stable_id"),
            },
        ),
        migrations.AddField(
            model_name="scopecoveragerequirement",
            name="official_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coverage_requirements",
                to="curriculum.subjectofficialtopic",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectofficialtopic",
            constraint=models.UniqueConstraint(
                fields=("manifest", "stable_id"), name="subject_official_topic_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectofficialtopic",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                name="subject_official_topic_sha256_format",
            ),
        ),
    ]
