# Generated by Django 5.2.17 on 2026-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0009_postgres_subject_official_topic_immutability"),
        ("official_scope", "0005_alter_officialscopeitem_knowledge_treatment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subjectofficialtopic",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("parent__isnull", False), ("root_scope_item__isnull", True)),
                    models.Q(("parent__isnull", True), ("root_scope_item__isnull", False)),
                    _connector="OR",
                ),
                name="subject_official_topic_exact_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectofficialtopic",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_terminal", True),
                        ("knowledge_treatment", "RECALLED_REQUIRED"),
                        ("official_marker", "STARRED"),
                        ("planning_group__isnull", False),
                    ),
                    models.Q(
                        ("is_terminal", True),
                        (
                            "knowledge_treatment",
                            "RECOGNITION_WITH_OR_WITHOUT_RESOURCES",
                        ),
                        ("official_marker", "UNSTARRED"),
                        ("planning_group__isnull", False),
                    ),
                    models.Q(
                        ("is_terminal", False),
                        ("knowledge_treatment", "UNSPECIFIED"),
                        ("official_marker", "NONE"),
                        ("planning_group__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="subject_official_topic_terminal_treatment",
            ),
        ),
    ]
