# Generated by Django 5.2.17 on 2026-09-02 22:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

TABLES = (
    "curriculum_subjectauthorityacquisition",
    "curriculum_candidaterequirementmapping",
)


def install_postgres_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in TABLES:
        trigger = f"{table}_no_mutation"
        schema_editor.execute(
            f"""
            CREATE TRIGGER {trigger}
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION curriculum_reject_immutable_mutation();
            """
        )


def remove_postgres_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in TABLES:
        trigger = f"{table}_no_mutation"
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table};")


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0010_subjectofficialtopic_subject_official_topic_exact_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityevidence",
            name="proposition_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="CandidateRequirementMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inherited_treatment", models.CharField(max_length=48)),
                ("mapping_rationale", models.TextField()),
                ("canonical_sha256", models.CharField(max_length=64)),
                (
                    "obligation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_requirement_mapping",
                        to="curriculum.ruleobligation",
                    ),
                ),
                (
                    "official_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_mappings",
                        to="curriculum.subjectofficialtopic",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_mappings",
                        to="curriculum.coveragerequirementslot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                        name="candidate_requirement_mapping_sha256_format",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectAuthorityAcquisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("proposition_types", models.JSONField(default=list)),
                ("locators", models.JSONField(default=list)),
                ("canonical_sha256", models.CharField(max_length=64)),
                ("acquired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_plan_acquisitions",
                        to="curriculum.authoritysource",
                    ),
                ),
                (
                    "authority_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acquisitions",
                        to="curriculum.subjectauthorityplan",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_acquisitions",
                        to="curriculum.scopecoveragerequirement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("authority_plan", "requirement", "authority"),
                        name="subject_authority_acquisition_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("canonical_sha256__regex", "^[0-9a-f]{64}$")),
                        name="subject_authority_acquisition_sha256_format",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_postgres_triggers, remove_postgres_triggers),
    ]
