# Generated by Django 5.2.17 on 2026-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0011_federal_question_candidate_foundation"),
        ("official_scope", "0005_alter_officialscopeitem_knowledge_treatment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="curriculumcompileversion",
            name="one_certified_curriculum_per_scope",
        ),
        migrations.AddConstraint(
            model_name="curriculumcompileversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("coverage_class", "NATIONAL"),
                    ("source_class", "PRODUCTION"),
                    ("status", "CERTIFIED"),
                ),
                fields=("official_scope_version",),
                name="one_certified_curriculum_per_scope",
            ),
        ),
    ]
